# Generated by Django 3.1.2 on 2020-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, unique=True)),
                ('picPlace', models.ImageField(null=True, upload_to='')),
                ('kwPlace', models.IntegerField(null=True)),
            ],
        ),
    ]
