# Generated by Django 3.1.2 on 2020-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_auto_20201025_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='kwPlace',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
