# Generated by Django 3.1.2 on 2020-10-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20201025_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(blank=True, max_length=33, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electricityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='electricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwp', models.IntegerField(blank=True, null=True)),
                ('paneleM2', models.TextField(blank=True, max_length=355, null=True)),
                ('sztukiPaneli', models.CharField(blank=True, max_length=70, null=True)),
                ('price_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.electricityprice')),
            ],
        ),
    ]
