# Generated by Django 3.1.2 on 2020-10-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20201025_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricdata',
            name='paneleM2',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
