# Generated by Django 3.1.2 on 2020-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_auto_20201025_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='użytkownik nie', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, default='podał dancyh', max_length=20, null=True),
        ),
    ]
