# Generated by Django 3.1.2 on 2020-10-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_auto_20201026_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricdata',
            old_name='paneleM2',
            new_name='panele_m2',
        ),
        migrations.RenameField(
            model_name='electricdata',
            old_name='sztukiPaneli',
            new_name='sztuki_paneli',
        ),
        migrations.RenameField(
            model_name='gallerymodel',
            old_name='kwPlace',
            new_name='kw_place',
        ),
        migrations.RenameField(
            model_name='gallerymodel',
            old_name='picPlace',
            new_name='pic_place',
        ),
    ]
