# Generated by Django 3.1.2 on 2020-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_auto_20201027_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
