# Generated by Django 3.1.2 on 2020-10-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_client_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='price_range',
        ),
    ]
