# Generated by Django 3.1.2 on 2020-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0014_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
